{{- if .Values.ingressPatreonWebhook.enabled -}}
{{- $fullName := include "ldtteam-authentication-server.fullname" . | printf "%s-patreon-webhook" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "ldtteam-authentication-server.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 30m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 256k
    nginx.ingress.kubernetes.io/proxy-buffering: 'on'
    nginx.ingress.kubernetes.io/proxy-buffers-number: '4'
    nginx.ingress.kubernetes.io/proxy-max-temp-file-size: 1024m
    {{- if .Values.ingressPatreonWebhook.annotations }}
    {{ toYaml .Values.ingressPatreonWebhook.annotations }}
    {{- end }}
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
       - {{ .Values.ingressPatreonWebhook.hostname }}
      secretName: auth-minecolonies-tls
  rules:
    - host: {{ .Values.ingressPatreonWebhook.hostname | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
