{{- if .Values.postgresha.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "ldtteam-authentication-server.fullname" . }}
spec:
  instances: 3
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql-minimal-trixie
    major: 17
  bootstrap:
    initdb:
      import:
        type: monolith
        databases:
          - authentication
          - github
          - patreon
        roles:
          - ldtteam-donator-auth
        source:
          externalCluster: legacy-instance
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: postgres-storage
      volumeMode: Filesystem
  externalClusters:
    - name: legacy-instance
      connectionParameters:
        # Use the correct IP or host name for the source database
        host: donator-auth-postgresql.donator-auth.svc.cluster.local
        user: postgres
        dbname: postgres
      password:
        name: legacy-instance-password
        key: password
---
apiVersion: v1
kind: Secret
metadata:
  name: legacy-instance-password
type: Opaque
stringData:
  password: ClZZNF6uzD
{{- end}}

    