{{- if .Values.postgresha.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: donator-auth
spec:
  instances: 3
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql-minimal-trixie
    major: 17
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: postgres-storage
      volumeMode: Filesystem
{{- end}}

    