apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: donator-auth
    app.kubernetes.io/name: postgresql
  name: data-donator-auth-postgresql-0
  namespace: donator-auth
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: pvc-67bb51eb-6c0a-4cc7-a3b8-88fd2e814954