{{- $databases := list "reward-api" }}
{{- if .Values.rewardApiService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ldtteam-authentication-server.fullname" . }}-reward-api-service
  labels:
    {{- include "ldtteam-authentication-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: reward-api-service
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ldtteam-authentication-server.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: reward-api-service
  template:
    metadata:
      labels:
        {{- include "ldtteam-authentication-server.labels" . | nindent 8 }}
        app.kubernetes.io/component: reward-api-service
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ldtteam-authentication-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: rewards-service
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.rewardApiService.repository }}:{{ .Values.rewardApiService.version | default .Chart.Version }}"
          imagePullPolicy: {{ .Values.rewardApiService.pullPolicy | default .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
          volumeMounts:
            - name: appsettings
              mountPath: /app/appsettings.json
              subPath: appsettings.json
            - name: secrets
              mountPath: /app/privateKey.pem
              readOnly: true
              subPath: privateKey.pem
          envFrom:
            - configMapRef:
                name: {{ include "ldtteam-authentication-server.fullname" . }}-environment
          env:
            - name: "VERSION"
              value: "{{ .Values.rewardApiService.version | default .Chart.Version }}"
            {{- if .Values.postgresha.enabled }}
            {{- range $db := $databases }}
            - name: LDTTEAM_AUTH_Database__Uris__{{ camelcase $db }}
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-%s-app" ( include "ldtteam-authentication-server.fullname" $ ) $db }}
                  key: uri
            {{- end }}
            {{- end }}
      volumes:
        - name: appsettings
          configMap:
            name: {{ include "ldtteam-authentication-server.fullname" . }}-appsettings
        - name: secrets
          secret:
            secretName: {{ include "ldtteam-authentication-server.opssecret" . }}
            items:
              - key: Github.PrivateKey
                path: privateKey.pem
{{- end }}
